# Generated by Django 4.2 on 2026-09-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sexe",
            field=models.CharField(
                choices=[("Homme", "homme"), ("Femme", "femme")],
                max_length=15,
                null=True,
            ),
        ),
    ]
