# Generated by Django 6.1.1 on 2026-09-16 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_categorie', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('déscription', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculté',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_faculte', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('déscription', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Département',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_departement', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('déscription', models.TextField(blank=True)),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='départements', to='academic.faculté')),
            ],
        ),
        migrations.CreateModel(
            name='Filière',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_filiere', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('déscription', models.TextField(blank=True)),
                ('département', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filières', to='academic.département')),
            ],
        ),
    ]
